apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sba

resources:
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: redis-streams-exporter
    files:
      - exporter.py