apiVersion: v1
kind: Service
metadata:
  name: redis-streams-exporter
  namespace: sba
  labels:
    app: redis-streams-exporter
spec:
  selector:
    app: redis-streams-exporter
  ports:
  - name: http
    port: 8000
    targetPort: http