apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-redis-streams-autoscale
  namespace: sba
spec:
  scaleTargetRef:
    name: worker
  pollingInterval: 10
  cooldownPeriod: 90
  minReplicaCount: 2
  maxReplicaCount: 50
  triggers:
    - type: redis-streams
      metadata:
        address: redis.sba.svc.cluster.local:6379
        stream: agent-jobs
        consumerGroup: workers
        lagCount: "3"
        activationLagCount: "1"
        enableTLS: "false"
        databaseIndex: "0"