apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sba

resources:
  - namespace.yaml
  - secret.yaml
  - postgres/postgres.yaml
  - redis/redis.yaml
  - orchestrator/orchestrator.yaml
  - worker/worker.yaml
  - postgres/migrate.yaml

