apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sba

resources:
  - namespace.yaml
  - secret.yaml
  - postgres/postgres.yaml
  - postgres/migrate.yaml
  - redis/redis.yaml
  - redis/scaledobject-redis-streams.yaml
  - orchestrator/orchestrator.yaml
  - orchestrator/gc-cronjob.yaml
  - worker/worker.yaml
  - worker/worker-pdb.yaml
  - monitoring/redis-streams-exporter 

